# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.5.4.dev29+g1065c40.d20230913'
__version_tuple__ = version_tuple = (0, 5, 4, 'dev29', 'g1065c40.d20230913')
