dataset_settings:
  f_s: 4096
  time_psd: 1024
  T: 8.0
  window:
    roll_off: 0.4
    type: tukey
  time_gap: 0          # specifies the time skipped between to consecutive PSD estimates. If set < 0, the time segments overlap
  num_psds_max: 1  # if set > 0, only a subset of all available PSDs will be used
  detectors:
    - H1
    - L1
  observing_run: O1