mass_1: bilby.core.prior.Constraint(minimum=10.0, maximum=80.0, name='mass_1')
mass_2: bilby.core.prior.Constraint(minimum=10.0, maximum=80.0, name='mass_2')
chirp_mass: bilby.gw.prior.UniformInComponentsChirpMass(minimum=15.0, maximum=100.0, name='chirp_mass')
mass_ratio: bilby.gw.prior.UniformInComponentsMassRatio(minimum=0.125, maximum=1.0, name='mass_ratio')
phase: default
chi_1: bilby.gw.prior.AlignedSpin(name='chi_1', a_prior=Uniform(minimum=0, maximum=0.9))
chi_2: bilby.gw.prior.AlignedSpin(name='chi_2', a_prior=Uniform(minimum=0, maximum=0.9))
theta_jn: default
luminosity_distance: 100.0
geocent_time: 0.0
