_target_: bilby.gw.prior.BBHPriorDict
_convert_: all
dictionary:
  mass_1: bilby.core.prior.Constraint(minimum=10.0, maximum=120.0, name='mass_1')
  mass_2: bilby.core.prior.Constraint(minimum=10.0, maximum=120.0, name='mass_2')
  chirp_mass: bilby.gw.prior.UniformInComponentsChirpMass(minimum=20.0, maximum=120.0, name='chirp_mass')
  mass_ratio: bilby.gw.prior.UniformInComponentsMassRatio(minimum=0.125, maximum=1.0, name='mass_ratio')
  phase: bilby.core.prior.Uniform(minimum=0.0, maximum=2*np.pi, boundary="periodic", name="phase")
  a_1: bilby.core.prior.Uniform(minimum=0.0, maximum=0.99, name='a_1')
  a_2: bilby.core.prior.Uniform(minimum=0.0, maximum=0.99, name='a_2')
  tilt_1: bilby.core.prior.Sine(minimum=0.0, maximum=np.pi, name='tilt_1')
  tilt_2: bilby.core.prior.Sine(minimum=0.0, maximum=np.pi, name='tilt_2')
  phi_12: bilby.core.prior.Uniform(minimum=0.0, maximum=2*np.pi, boundary="periodic", name="phi_12")
  phi_jl: bilby.core.prior.Uniform(minimum=0.0, maximum=2*np.pi, boundary="periodic", name="phi_jl")
  theta_jn: bilby.core.prior.Sine(minimum=0.0, maximum=np.pi, name='theta_jn')
  luminosity_distance: 100.0
  geocent_time: 0.0
