mass_1: bilby.core.prior.Constraint(minimum=10.0, maximum=80.0, name='mass_1')
mass_2: bilby.core.prior.Constraint(minimum=10.0, maximum=80.0, name='mass_2')
chirp_mass: bilby.gw.prior.UniformInComponentsChirpMass(minimum=15.0, maximum=100.0, name='chirp_mass')
mass_ratio: bilby.gw.prior.UniformInComponentsMassRatio(minimum=0.125, maximum=1.0, name='mass_ratio')
phase: default
a_1: bilby.core.prior.Uniform(minimum=0.0, maximum=0.88, name='a_1')
a_2: bilby.core.prior.Uniform(minimum=0.0, maximum=0.88, name='a_2')
tilt_1: default
tilt_2: default
phi_12: default
phi_jl: default
theta_jn: default
luminosity_distance: 100.0
geocent_time: 0.0
