defaults:
  - hydra: default
  - domain: multibanded_frequency
  - waveform_generator: phenom_xphm
  - intrinsic_prior: precessing_multibanded_test
  - _self_

num_samples: 1
compression: null

hydra:
  job:
    name: evaluate_multibanded_domain
