defaults:
  - domain: uniform_frequency
  - waveform_generator: phenom_d
  - _self_

intrinsic_prior:
  _target_: bilby.gw.prior.BBHPriorDict
  _convert_: all
  dictionary:
    mass_1: bilby.core.prior.Constraint(minimum=10.0, maximum=80.0, name='mass_1')
    mass_2: bilby.core.prior.Constraint(minimum=10.0, maximum=80.0, name='mass_2')
    chirp_mass: bilby.gw.prior.UniformInComponentsChirpMass(minimum=15.0, maximum=100.0, name='chirp_mass')
    mass_ratio: bilby.gw.prior.UniformInComponentsMassRatio(minimum=0.125, maximum=1.0, name='mass_ratio')
    phase: bilby.core.prior.Uniform(minimum=0.0, maximum=2*np.pi, boundary="periodic", name="phase")
    chi_1: bilby.gw.prior.AlignedSpin(name='chi_1', a_prior=Uniform(minimum=0, maximum=0.9))
    chi_2: bilby.gw.prior.AlignedSpin(name='chi_2', a_prior=Uniform(minimum=0, maximum=0.9))
    theta_jn: bilby.core.prior.Sine(minimum=0.0, maximum=np.pi, name='theta_jn')
    luminosity_distance: 100.0
    geocent_time: 0.0

num_samples: 10000
compression: null
num_processes: 1
out_file: waveform_dataset.hdf5

hydra:
  run:
    dir: ${oc.env:DINGO_RUNS}/${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.name}_${hydra.job.override_dirname}
  job:
    name: generate_dataset
    chdir: true
  job_logging:
    loggers:
      bilby:
        level: INFO
        propagate: true
