defaults:
  - hydra: default
  - model: unconditional_npe
  - optimizer: adam
  - scheduler: cosine
  - _self_

outdir: .
parameter_samples: ???
num_samples: 1000
event_dataset: null
time_marginalization:
  n_fft: 5
phase_marginalization: null
synthetic_phase: null
calibration_marginalization: null
num_processes: 1

slice_plots:
  num_slice_plots: 10
  params_slice2d:
    - [phase, geocent_time]
    - [phase, tilt_1]

nde:
  path: null
  data:
    parameter_samples: null
    parameters: null
  model: ${model}
  training:
    optimizer: ${optimizer}
    scheduler: ${scheduler}
    device: cpu
    num_workers: 0
    train_fraction: 0.9
    batch_size: 512
    epochs: 20

hydra:
  job:
    name: importance_weights
    config:
      override_dirname:
        exclude_keys:
          - parameter_samples
          - nde.path
