defaults:
  - model: toy_npe
  - _self_

checkpoint: null
train_dir: train
exit_command: ""

extrinsic_prior:
  _target_: dingo.gw.prior.BBHExtrinsicPriorDict
  _convert_: all
  dictionary:
    dec: bilby.core.prior.Cosine(minimum=-np.pi/2, maximum=np.pi/2, name='dec')
    ra: bilby.core.prior.Uniform(minimum=0., maximum=2*np.pi, boundary="periodic", name="ra")
    geocent_time: bilby.core.prior.Uniform(minimum=-0.10, maximum=0.10, name='geocent_time')
    psi: bilby.core.prior.Uniform(minimum=0.0, maximum=np.pi, boundary="periodic", name="psi")
    luminosity_distance: bilby.core.prior.Uniform(minimum=100.0, maximum=1000.0, name='luminosity_distance')

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 20

data:
  extrinsic_prior: ${extrinsic_prior}
  waveform_dataset:
    _target_: dingo.gw.dataset.WaveformDataset
    file_name: training_data/waveform_dataset.hdf5
    precision: single
    domain_update: null
    svd_size_update: null
  train_fraction: 0.95
  detectors:
    - H1
    - L1
  ref_time: 1126259462.391
  gnpe_time_shifts: null
  random_strain_cropping: null
  inference_parameters:
    - chirp_mass
    - mass_ratio
    - chi_1
    - chi_2
    - theta_jn
    - dec
    - ra
    - geocent_time
    - luminosity_distance
    - psi
    - phase
  context_parameters: []
  selected_keys:
    - inference_parameters
    - waveform
  standardization:
    mean: ???
    std: ???
  standardization_transforms:
    - _target_: dingo.gw.transforms.SampleExtrinsicParameters
      extrinsic_prior_dict: ${data.extrinsic_prior}
    - _target_: dingo.gw.transforms.GetDetectorTimes
      ifo_list:
        _target_: bilby.gw.detector.InterferometerList
        interferometers: ${data.detectors}
      ref_time: ${data.ref_time}
  transforms:
    - _target_: dingo.gw.transforms.SampleExtrinsicParameters
      extrinsic_prior_dict: ${data.extrinsic_prior}
    - _target_: dingo.gw.transforms.GetDetectorTimes
      ifo_list:
        _target_: bilby.gw.detector.InterferometerList
        interferometers: ${data.detectors}
      ref_time: ${data.ref_time}
    - _target_: dingo.gw.transforms.ProjectOntoDetectors
      _partial_: true
      _runtime_dependencies_: [domain]
      ifo_list:
        _target_: bilby.gw.detector.InterferometerList
        interferometers: ${data.detectors}
      ref_time: ${data.ref_time}
    - _target_: dingo.gw.transforms.SampleNoiseASD
      _partial_: true
      _runtime_dependencies_: [asd_dataset]
    - _target_: dingo.gw.transforms.WhitenAndScaleStrain
      _partial_: true
      _runtime_dependencies_: [domain]
    - _target_: dingo.gw.transforms.AddWhiteNoiseComplex
    - _target_: dingo.gw.transforms.SelectStandardizeRepackageParameters
      parameters_dict:
        inference_parameters: ${data.inference_parameters}
        context_parameters: ${data.context_parameters}
      standardization_dict: ${data.standardization}
    - _target_: dingo.gw.transforms.RepackageStrainsAndASDS
      _partial_: true
      _runtime_dependencies_: [domain]
      ifos: ${data.detectors}
    - _target_: dingo.gw.transforms.UnpackDict
      selected_keys: ${data.selected_keys}

training:
  evaluate: false
  stage_0:
    optimizer: ${optimizer}
    scheduler: ${scheduler}
    epochs: 20
    asd_dataset:
      _target_: dingo.gw.noise.asd_dataset.ASDDataset
      file_name: training_data/asd_dataset/asds_O1.hdf5
      ifos: ${data.detectors}
      precision: single
      domain_update: null
    freeze_rb_layer: true
    batch_size: 64
    early_stopping: null

local:
  device: cpu
  num_workers: 6
  runtime_limits:
    max_time_per_run: 3600000
    max_epochs_per_run: 30
  checkpoint_epochs: 15
  leave_waveforms_on_disk: true
  local_cache_path: null
  wandb: false
  test_only: false

hydra:
  run:
    dir: ${oc.env:DINGO_RUNS}/${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.name}_${hydra.job.override_dirname}
  job:
    name: train
    chdir: true
  job_logging:
    loggers:
      bilby:
        level: INFO
        propagate: true
