#!/usr/bin/env python3
"""
Command-line interface for plotting waveforms generated by dingo.

This tool generates waveforms from a JSON configuration file and creates
interactive plots for visualization and diagnostics.
"""
import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Dict, Any, Optional

from dingo.gw.domains import TimeDomain, UniformFrequencyDomain, MultibandedFrequencyDomain
from dingo.gw.waveform_generator.new_api import build_waveform_generator
from dingo.gw.waveform_generator.waveform_parameters import BBHWaveformParameters
from dingo.gw.logs import set_logging
from . import (
    plot_polarizations_time,
    plot_polarizations_frequency,
    plot_polarization_spectrogram,
    plot_polarization_qtransform,
    plot_mode_amplitudes,
    plot_individual_modes,
    plot_mode_comparison,
    plot_modes_grid,
)


def load_config(config_path: str) -> Dict[str, Any]:
    """Load configuration from JSON file."""
    path = Path(config_path)
    if not path.exists():
        raise FileNotFoundError(f"Configuration file not found: {config_path}")

    with open(path, "r") as f:
        config = json.load(f)

    return config


def validate_config(config: Dict[str, Any]) -> None:
    """Validate configuration has required fields."""
    required_fields = ["domain", "waveform_generator", "waveform_parameters"]
    missing = [f for f in required_fields if f not in config]

    if missing:
        raise ValueError(
            f"Configuration missing required fields: {', '.join(missing)}\n"
            f"Required fields: {', '.join(required_fields)}"
        )

    if "type" not in config["domain"]:
        raise ValueError("domain.type is required")

    if "approximant" not in config["waveform_generator"]:
        raise ValueError("waveform_generator.approximant is required")

    if not isinstance(config["waveform_parameters"], dict):
        raise ValueError("waveform_parameters must be a dictionary")


def create_waveform_parameters(params_config: Dict[str, Any]) -> BBHWaveformParameters:
    """Create BBHWaveformParameters from configuration."""
    return BBHWaveformParameters(**params_config)


def save_or_show_plot(fig, filename: Optional[str], show: bool):
    """Save plot to file and/or display it."""
    if filename:
        fig.write_html(filename)
        print(f"  Saved to {filename}")

    if show:
        fig.show()


def plot_basic_polarizations(
    wfg,
    params: BBHWaveformParameters,
    domain,
    output_dir: Path,
    show: bool,
    logger: logging.Logger,
):
    """Generate and plot basic polarizations (from generate_hplus_hcross)."""
    logger.info("Generating basic polarizations...")
    pol = wfg.generate_hplus_hcross(params)
    logger.info(f"  h_plus shape: {pol.h_plus.shape}")
    logger.info(f"  h_cross shape: {pol.h_cross.shape}")

    domain_type = None
    if isinstance(domain, TimeDomain):
        domain_type = "time"
    elif isinstance(domain, (UniformFrequencyDomain, MultibandedFrequencyDomain)):
        domain_type = "frequency"

    logger.info("Creating polarization plots...")

    if domain_type == "time":
        fig1 = plot_polarizations_time(pol, domain)
        save_or_show_plot(fig1, output_dir / "polarizations_time.html", show)

        logger.info("  Creating spectrogram...")
        fig2 = plot_polarization_spectrogram(pol, domain)
        save_or_show_plot(fig2, output_dir / "spectrogram.html", show)

        logger.info("  Creating Q-transform...")
        fig3 = plot_polarization_qtransform(pol, domain)
        save_or_show_plot(fig3, output_dir / "qtransform.html", show)

    elif domain_type == "frequency":
        fig1 = plot_polarizations_frequency(pol, domain, plot_type="amplitude")
        save_or_show_plot(fig1, output_dir / "polarizations_amplitude.html", show)

        fig2 = plot_polarizations_frequency(pol, domain, plot_type="both")
        save_or_show_plot(fig2, output_dir / "polarizations_both.html", show)


def plot_mode_separated(
    wfg,
    params: BBHWaveformParameters,
    domain,
    output_dir: Path,
    show: bool,
    logger: logging.Logger,
):
    """Generate and plot mode-separated polarizations (from generate_hplus_hcross_m)."""
    logger.info("Generating mode-separated polarizations...")
    modes = wfg.generate_hplus_hcross_m(params)
    logger.info(f"  Number of modes: {len(modes)}")
    logger.info(f"  Modes: {sorted(modes.keys())}")

    logger.info("Creating mode plots...")

    fig1 = plot_mode_amplitudes(modes, domain)
    save_or_show_plot(fig1, output_dir / "mode_amplitudes.html", show)

    fig2 = plot_individual_modes(
        modes,
        domain,
        domain_type="time" if isinstance(domain, TimeDomain) else "frequency",
    )
    save_or_show_plot(fig2, output_dir / "individual_modes.html", show)

    if len(modes) > 1:
        reference_mode = max(modes.keys(), key=abs)
        fig3 = plot_mode_comparison(modes, domain, reference_mode=reference_mode)
        save_or_show_plot(fig3, output_dir / "mode_comparison.html", show)

    if len(modes) > 2:
        fig4 = plot_modes_grid(
            modes,
            domain,
            domain_type="time" if isinstance(domain, TimeDomain) else "frequency",
        )
        save_or_show_plot(fig4, output_dir / "modes_grid.html", show)


def main():
    """Main entry point for CLI."""
    parser = argparse.ArgumentParser(
        description="Generate and plot waveforms from dingo",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  dingo-plot --config config.json
  dingo-plot --config config.json --modes
  dingo-plot --config config.json --output plots/ --show
        """,
    )

    parser.add_argument(
        "--config",
        "-c",
        default="config.json",
        help="Path to JSON configuration file (default: config.json)",
    )
    parser.add_argument(
        "--modes",
        "-m",
        action="store_true",
        help="Plot mode-separated waveforms instead of basic polarizations.",
    )
    parser.add_argument(
        "--output",
        "-o",
        default=".",
        help="Output directory for plot HTML files (default: current directory)",
    )
    parser.add_argument(
        "--show",
        "-s",
        action="store_true",
        help="Display plots in browser (in addition to saving them)",
    )

    args = parser.parse_args()

    set_logging()
    logger = logging.getLogger(__name__)

    try:
        logger.info(f"Loading configuration from: {args.config}")
        config = load_config(args.config)
        validate_config(config)

        output_dir = Path(args.output)
        output_dir.mkdir(parents=True, exist_ok=True)

        logger.info("Creating waveform generator from configuration...")
        wfg = build_waveform_generator(config)

        domain = wfg._waveform_gen_params.domain
        approximant = wfg._waveform_gen_params.approximant

        logger.info(f"  Domain: {type(domain).__name__}")
        logger.info(f"  Approximant: {approximant}")

        logger.info("Creating waveform parameters...")
        params = create_waveform_parameters(config["waveform_parameters"])

        if args.modes:
            plot_mode_separated(wfg, params, domain, output_dir, args.show, logger)
        else:
            plot_basic_polarizations(wfg, params, domain, output_dir, args.show, logger)

        logger.info("Plotting complete!")
        logger.info(f"Plots saved to: {output_dir.absolute()}")

        sys.exit(0)

    except FileNotFoundError as e:
        logger.error(f"Error: {e}")
        sys.exit(1)
    except ValueError as e:
        logger.error(f"Configuration Error: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected Error: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
