# Running pytest upon push to main or upon merge request in main

name: Pytest for Dingo-GW

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: Pytest for Dingo-GW on Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
    runs-on: ubuntu-latest
    env:
      OPENBLAS_NUM_THREADS: 1
      MKL_NUM_THREADS: 1
      NUMEXPR_NUM_THREADS: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev]
          pip install -U "htcondor<23"

      - name: Run Pytest
        run: |
          python -m pytest --junit-xml=pytest-report.xml --ignore tests/asimov tests/

      - name: Run Asimov integration tests
        run: |
          pytest -m asimov --junit-xml=pytest-asimov-report.xml tests/

      - name: Upload Pytest Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-${{ matrix.python-version }}.xml
          path: pytest-report.xml
          retention-days: 30
